### PR TITLE
switched from base to {rlang} messages, warnings and errors

### PR DESCRIPTION
**Pull request by TomekMatuszek**

### CODE REVIEW

**Comment by Nowosad** [comment]
@TomekMatuszek, two comments:

1. Why there is `Warning: Unknown or uninitialised column: `fullness`.`?
2. I think that it should be possible to disable the progress bar in all the functions


``` r
devtools::load_all()
#> ℹ Loading vectormetrics
vm_c_fullness(vector_landscape, class_col = "class")
#> MULTIPOLYGON geometry provided. You may want to cast it to separate polygons with 'get_patches()'.
#> This message is displayed once per session.
#>   |                                                                              |                                                                      |   0%
#> Warning: Unknown or uninitialised column: `fullness`.
#>   |                                                                              |=======================                                               |  33%  |                                                                              |===============================================                       |  67%  |                                                                              |======================================================================| 100%
#> # A tibble: 3 × 5
#>   level class    id metric     value
#>   <chr> <int> <int> <chr>      <dbl>
#> 1 class     1    NA full_index 0.883
#> 2 class     2    NA full_index 0.903
#> 3 class     3    NA full_index 0.894
```

**Comment by TomekMatuszek** [comment]
1. I initialized column correctly in `vm_p_fullness`. It is weird, that this warning only showed up when `vm_p_fullness` was used inside `vm_c_fullness`, but now it works OK.
2. I added new parameter to `vm_p_fullness` and `vm_p_proxim` that makes progress bar optional, but with default set to `TRUE`.

**Comment by Nowosad** [comment]
👍🏻

**Comment by Nowosad** [comment]
@TomekMatuszek please update the package version and rerender the README file. Then -- feel free to merge the PR

**Pull request merged**
